language: python
matrix:
  include:
    - python: "3.5.3"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
      dist: xenial
    - python: "3.6"
      env: TOXENV=lint
      env: TOXENV=pytype
install: pip install tox
script: tox
